// app/layout.tsx
import "../styles/globals.css";
import type { Metadata } from "next";
import Navbar from "../components/Navbar";
import React from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="scroll-smooth antialiased [font-feature-settings:'ss01']">
        <Navbar />
        {/* You can wrap children in a container for consistent spacing */}
        <main className="mx-auto w-full max-w-screen-xl p-6">{children}</main>
      </body>
    </html>
  );
}
